const constants = {
    TYPE_MENU: "M",
    TYPE_MENU_COMPONENT: "P",
    TYPE_FAST_FOOD: "F",
    TYPE_FAST_FOOD_INGREDIENT: "W",
    TYPE_TAPA: "T",
    TYPE_WINE: "V",
    TYPE_COMBINED: "C",
    TYPE_LIQUOR: "L",
    TYPE_SIX_TYPES: "Z",
    TYPE_KITCHEN_NOTICE: "I",
    NO_GROUP: 0,
    MENU_COMPONENT_TEXT: "Menú ",
    TREAT_TEXT: "Invita.",
    DISCOUNT_TEXT: ".DTO.",
    INGREDIENT_TYPE_BASIC: 0,
    INGREDIENT_TYPE_EXTRA: 1,
    FAST_FOOD_FULL: 0,
    FAST_FOOD_FIRST_HALF: 1,
    FAST_FOOD_SECOND_HALF: 2,

    PERMISSION_DELETE_LINE: "Del",
    PERMISSION_DELETE_LINE_KITCHEN: "DelK",
    PERMISSION_DELETE_LINE_PRINTED: "DelP",
    PERMISSION_EDIT_PRICE: "EdP",
    PERMISSION_EDIT_QUANTITY: "EdQ",
    PERMISSION_DISCOUNT: "Dic",
    PERMISSION_TREAT: "Tr",
    PERMISSION_MOVE_LINE: "Mo"
}

export default constants;