const constants = {
    KITCHEN_REFRESH: 1,
    SEND_GROUPS: 2,
    SEND_MAKING_PLACES: 3,
    LINE_MARKED_DONE: 4,
    CONNECTION_OPEN: 5,
    SEND_OPERATORS: 6,
    SEND_PLACES: 7,
    SEND_TABLES: 8,
    SEND_FAMILY_TREE: 9,
    OPERATOR_OPEN: 10,
    SEND_TABLE: 11,
    SEND_SCHEDULE: 12,
    SEND_CALIFICATORS: 13,
    TICKET_MOVED: 14,
    CONNECTION_ACCEPTED: 15,
    OPERATOR_CLOSE: 16,
    PING: 17,
    PERMISSION_RESPONSE: 18,
    SEND_CLIENTS: 19,
    SEND_PAYMENT_WAYS: 20,
    TABLE_OPEN: 21,
    PRODUCT_STOCK: 22,
    PLACE_NOTIFICATIONS: 23,
    HOTEL_ROOM: 24,
    SEND_PRODUCTS: 25, // 👈 nuevo cliente protocol 
}

export default constants;